//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 414
#pragma warning disable 649
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Orleans.PingPong
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Orleans.PingPong;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ClientFactory
    {
        

                        public static Orleans.PingPong.IClient GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IClient), 523268002, primaryKey));
                        }

                        public static Orleans.PingPong.IClient GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IClient), 523268002, primaryKey, grainClassNamePrefix));
                        }

                        public static Orleans.PingPong.IClient GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IClient), 523268002, primaryKey));
                        }

                        public static Orleans.PingPong.IClient GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IClient), 523268002, primaryKey, grainClassNamePrefix));
                        }

            public static Orleans.PingPong.IClient Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ClientReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Orleans.PingPong.Orleans.PingPong.IClient")]
        internal class ClientReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Orleans.PingPong.IClient
        {
            

            public static Orleans.PingPong.IClient Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Orleans.PingPong.IClient) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Orleans.PingPong.IClient), (global::Orleans.Runtime.GrainReference gr) => { return new ClientReference(gr);}, grainRef, 523268002);
            }
            
            protected internal ClientReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ClientReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 523268002;
                }
            }
            
            public override string InterfaceName
            {
                get
                {
                    return "Orleans.PingPong.Orleans.PingPong.IClient";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ClientReference input = ((ClientReference)(original));
                return ((ClientReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ClientReference input = ((ClientReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ClientReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ClientMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Orleans.PingPong.IClient.Run()
            {

                return base.InvokeMethodAsync<object>(1975541297, null );
            }
            
            System.Threading.Tasks.Task Orleans.PingPong.IClient.Pong(Orleans.PingPong.IDestination @from, Orleans.PingPong.Message @message)
            {

                return base.InvokeMethodAsync<object>(-2060440583, new object[] {@from is global::Orleans.Grain ? @from.AsReference<Orleans.PingPong.IDestination>() : @from, @message} );
            }
            
            System.Threading.Tasks.Task Orleans.PingPong.IClient.Initialize(Orleans.PingPong.IDestination @actor, long @repeats)
            {

                return base.InvokeMethodAsync<object>(1682027821, new object[] {@actor is global::Orleans.Grain ? @actor.AsReference<Orleans.PingPong.IDestination>() : @actor, @repeats} );
            }
            
            System.Threading.Tasks.Task Orleans.PingPong.IClient.Subscribe(Orleans.PingPong.IClientObserver @subscriber)
            {
global::Orleans.CodeGeneration.GrainFactoryBase.CheckGrainObserverParamInternal(@subscriber);

                return base.InvokeMethodAsync<object>(-1238941369, new object[] {@subscriber is global::Orleans.Grain ? @subscriber.AsReference<Orleans.PingPong.IClientObserver>() : @subscriber} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Orleans.PingPong.Orleans.PingPong.IClient", 523268002)]
    internal class ClientMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 523268002;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 523268002:  // IClient
                        switch (methodId)
                        {
                            case 1975541297: 
                                return ((IClient)grain).Run().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -2060440583: 
                                return ((IClient)grain).Pong((IDestination)arguments[0], (Message)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1682027821: 
                                return ((IClient)grain).Initialize((IDestination)arguments[0], (Int64)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1238941369: 
                                return ((IClient)grain).Subscribe((IClientObserver)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 523268002:  // IClient
                    switch (methodId)
                    {
                        case 1975541297:
                            return "Run";
                    case -2060440583:
                            return "Pong";
                    case 1682027821:
                            return "Initialize";
                    case -1238941369:
                            return "Subscribe";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class ClientObserverFactory
    {
        

            public static Orleans.PingPong.IClientObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return ClientObserverReference.Cast(grainRef);
            }

        private static global::Orleans.CodeGeneration.IGrainMethodInvoker methodInvoker;

        public async static System.Threading.Tasks.Task<Orleans.PingPong.IClientObserver> CreateObjectReference(Orleans.PingPong.IClientObserver obj)
        {
            if (methodInvoker == null) methodInvoker = new ClientObserverMethodInvoker();
            return ClientObserverFactory.Cast(await global::Orleans.Runtime.GrainReference.CreateObjectReference(obj, methodInvoker));
        }

        public static System.Threading.Tasks.Task DeleteObjectReference(Orleans.PingPong.IClientObserver reference)
        {
            return global::Orleans.Runtime.GrainReference.DeleteObjectReference(reference);
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Orleans.PingPong.Orleans.PingPong.IClientObserver")]
        internal class ClientObserverReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Orleans.PingPong.IClientObserver
        {
            

            public static Orleans.PingPong.IClientObserver Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Orleans.PingPong.IClientObserver) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Orleans.PingPong.IClientObserver), (global::Orleans.Runtime.GrainReference gr) => { return new ClientObserverReference(gr);}, grainRef, 1126410990);
            }
            
            protected internal ClientObserverReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal ClientObserverReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1126410990;
                }
            }
            
            public override string InterfaceName
            {
                get
                {
                    return "Orleans.PingPong.Orleans.PingPong.IClientObserver";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                ClientObserverReference input = ((ClientObserverReference)(original));
                return ((ClientObserverReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                ClientObserverReference input = ((ClientObserverReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return ClientObserverReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return ClientObserverMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            void Orleans.PingPong.IClientObserver.Done(long @pings, long @pongs)
            {

                    base.InvokeOneWayMethod(-1778340467, new object[] {@pings, @pongs} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Orleans.PingPong.Orleans.PingPong.IClientObserver", 1126410990)]
    internal class ClientObserverMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1126410990;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1126410990:  // IClientObserver
                        switch (methodId)
                        {
                            case -1778340467: 
                                ((IClientObserver)grain).Done((Int64)arguments[0], (Int64)arguments[1]); return System.Threading.Tasks.Task.FromResult((object)true);
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1126410990:  // IClientObserver
                    switch (methodId)
                    {
                        case -1778340467:
                            return "Done";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class DestinationFactory
    {
        

                        public static Orleans.PingPong.IDestination GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IDestination), 1662910789, primaryKey));
                        }

                        public static Orleans.PingPong.IDestination GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IDestination), 1662910789, primaryKey, grainClassNamePrefix));
                        }

                        public static Orleans.PingPong.IDestination GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IDestination), 1662910789, primaryKey));
                        }

                        public static Orleans.PingPong.IDestination GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.PingPong.IDestination), 1662910789, primaryKey, grainClassNamePrefix));
                        }

            public static Orleans.PingPong.IDestination Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return DestinationReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Orleans.PingPong.Orleans.PingPong.IDestination")]
        internal class DestinationReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Orleans.PingPong.IDestination
        {
            

            public static Orleans.PingPong.IDestination Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Orleans.PingPong.IDestination) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Orleans.PingPong.IDestination), (global::Orleans.Runtime.GrainReference gr) => { return new DestinationReference(gr);}, grainRef, 1662910789);
            }
            
            protected internal DestinationReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal DestinationReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1662910789;
                }
            }
            
            public override string InterfaceName
            {
                get
                {
                    return "Orleans.PingPong.Orleans.PingPong.IDestination";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                DestinationReference input = ((DestinationReference)(original));
                return ((DestinationReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                DestinationReference input = ((DestinationReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return DestinationReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return DestinationMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Orleans.PingPong.IDestination.Ping(Orleans.PingPong.IClient @from, Orleans.PingPong.Message @message)
            {

                return base.InvokeMethodAsync<object>(1491328371, new object[] {@from is global::Orleans.Grain ? @from.AsReference<Orleans.PingPong.IClient>() : @from, @message} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Orleans.PingPong.Orleans.PingPong.IDestination", 1662910789)]
    internal class DestinationMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1662910789;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1662910789:  // IDestination
                        switch (methodId)
                        {
                            case 1491328371: 
                                return ((IDestination)grain).Ping((IClient)arguments[0], (Message)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1662910789:  // IDestination
                    switch (methodId)
                    {
                        case 1491328371:
                            return "Ping";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.8.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Orleans_PingPong_MessageSerialization
    {
        
        static Orleans_PingPong_MessageSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Orleans.PingPong.Message input = ((Orleans.PingPong.Message)(untypedInput));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Orleans.PingPong.Message result = new Orleans.PingPong.Message();
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Orleans.PingPong.Message), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 414
#pragma warning restore 649
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
